/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Made Kids MK API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message: string;
}

export interface SuccessResponse {
  success: boolean;
  message: string;
}

export type RegisterBodyPlan =
  (typeof RegisterBodyPlan)[keyof typeof RegisterBodyPlan];

export const RegisterBodyPlan = {
  monthly: "monthly",
  annual: "annual",
} as const;

export interface RegisterBody {
  email: string;
  /** @minLength 8 */
  password: string;
  name: string;
  plan: RegisterBodyPlan;
}

export interface LoginBody {
  email: string;
  password: string;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  parent: "parent",
  admin: "admin",
} as const;

export type UserSubscriptionStatus =
  (typeof UserSubscriptionStatus)[keyof typeof UserSubscriptionStatus];

export const UserSubscriptionStatus = {
  active: "active",
  inactive: "inactive",
  trialing: "trialing",
} as const;

export interface User {
  id: number;
  email: string;
  name: string;
  role: UserRole;
  subscriptionStatus: UserSubscriptionStatus;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export interface AddChildBody {
  name: string;
  age: number;
  avatarUrl?: string;
}

export interface Child {
  id: number;
  parentId: number;
  name: string;
  age: number;
  avatarUrl?: string;
  totalPoints: number;
  currentStreak: number;
  createdAt: string;
}

export type SubscriptionPlanInterval =
  (typeof SubscriptionPlanInterval)[keyof typeof SubscriptionPlanInterval];

export const SubscriptionPlanInterval = {
  monthly: "monthly",
  annual: "annual",
} as const;

export interface SubscriptionPlan {
  id: string;
  name: string;
  price: number;
  interval: SubscriptionPlanInterval;
  description: string;
  features: string[];
}

export interface CreateSubscriptionBody {
  planId: string;
  paymentMethod?: string;
}

export type SubscriptionStatus =
  (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];

export const SubscriptionStatus = {
  active: "active",
  inactive: "inactive",
  canceled: "canceled",
  trialing: "trialing",
} as const;

export interface Subscription {
  id: number;
  userId: number;
  planId: string;
  status: SubscriptionStatus;
  currentPeriodStart?: string;
  currentPeriodEnd?: string;
  createdAt: string;
}

export interface DailyContent {
  id: number;
  date: string;
  title: string;
  description: string;
  videoUrl: string;
  thumbnailUrl?: string;
  /** Duration in seconds */
  duration: number;
  /** What the child should recite after watching */
  recitationPrompt: string;
  /** The daily challenge to perform */
  challengeDescription: string;
  /** Total points available for completing all three modules */
  pointsValue: number;
  /** Theme of the day (emotional intelligence, resilience, etc.) */
  theme: string;
  createdAt: string;
}

export interface MarkViewedBody {
  childId: number;
  /** Actual seconds watched by the child */
  watchedDuration: number;
  /** Whether fast-forward behavior was detected client-side */
  fastForwardDetected: boolean;
}

export interface ContentView {
  id: number;
  contentId: number;
  childId: number;
  watchedDuration: number;
  fastForwardDetected: boolean;
  completedAt?: string;
  pointsAwarded: number;
}

/**
 * recitation = reciting what was learned, challenge = performing the daily challenge
 */
export type SubmitRecordingBodyType =
  (typeof SubmitRecordingBodyType)[keyof typeof SubmitRecordingBodyType];

export const SubmitRecordingBodyType = {
  recitation: "recitation",
  challenge: "challenge",
} as const;

export interface SubmitRecordingBody {
  childId: number;
  contentId: number;
  /** recitation = reciting what was learned, challenge = performing the daily challenge */
  type: SubmitRecordingBodyType;
  /** Base64 encoded audio data URL */
  audioDataUrl: string;
  durationSeconds: number;
}

export type RecordingType = (typeof RecordingType)[keyof typeof RecordingType];

export const RecordingType = {
  recitation: "recitation",
  challenge: "challenge",
} as const;

export interface Recording {
  id: number;
  childId: number;
  contentId: number;
  type: RecordingType;
  audioUrl?: string;
  durationSeconds: number;
  pointsAwarded: number;
  submittedAt: string;
}

export type ProgressModulesCompletedTodayItem =
  (typeof ProgressModulesCompletedTodayItem)[keyof typeof ProgressModulesCompletedTodayItem];

export const ProgressModulesCompletedTodayItem = {
  video: "video",
  recitation: "recitation",
  challenge: "challenge",
} as const;

export interface Progress {
  childId: number;
  childName: string;
  totalPoints: number;
  pointsThisWeek: number;
  pointsThisMonth: number;
  pointsThisQuarter: number;
  modulesCompletedToday: ProgressModulesCompletedTodayItem[];
  daysActiveThisQuarter: number;
  quarterStartDate: string;
  quarterEndDate: string;
}

export interface DayCompletion {
  date: string;
  videoCompleted: boolean;
  recitationCompleted: boolean;
  challengeCompleted: boolean;
  pointsEarned: number;
}

export interface Streak {
  childId: number;
  currentStreak: number;
  longestStreak: number;
  lastActiveDate?: string;
  completionHistory: DayCompletion[];
}

export interface ProgressSummary {
  childId: number;
  quarterLabel: string;
  totalPoints: number;
  rank?: number;
  /** 0-100 percent */
  completionRate: number;
  /** Calculated improvement metric */
  improvementScore: number;
  eligibleForReward: boolean;
}

export interface LeaderboardEntry {
  rank: number;
  childId: number;
  childName: string;
  avatarUrl?: string;
  totalPoints: number;
  improvementScore: number;
  streak: number;
  isCurrentUser: boolean;
}

export interface Reward {
  id: number;
  title: string;
  description: string;
  destination: string;
  imageUrl?: string;
  quarterLabel: string;
  /** Number of kids selected per quarter */
  winnersCount: number;
  isActive: boolean;
}
