/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Made Kids MK API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AddChildBody,
  AuthResponse,
  Child,
  ContentView,
  CreateSubscriptionBody,
  DailyContent,
  ErrorResponse,
  HealthStatus,
  LeaderboardEntry,
  LoginBody,
  MarkViewedBody,
  Progress,
  ProgressSummary,
  Recording,
  RegisterBody,
  Reward,
  Streak,
  SubmitRecordingBody,
  Subscription,
  SubscriptionPlan,
  SuccessResponse,
  User,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new parent account
 */
export const getRegisterUserUrl = () => {
  return `/api/auth/register`;
};

export const registerUser = async (
  registerBody: RegisterBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getRegisterUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerBody),
  });
};

export const getRegisterUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  const mutationKey = ["registerUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    { data: BodyType<RegisterBody> }
  > = (props) => {
    const { data } = props ?? {};

    return registerUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerUser>>
>;
export type RegisterUserMutationBody = BodyType<RegisterBody>;
export type RegisterUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new parent account
 */
export const useRegisterUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterBody> },
  TContext
> => {
  return useMutation(getRegisterUserMutationOptions(options));
};

/**
 * @summary Login
 */
export const getLoginUserUrl = () => {
  return `/api/auth/login`;
};

export const loginUser = async (
  loginBody: LoginBody,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginBody),
  });
};

export const getLoginUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  const mutationKey = ["loginUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    { data: BodyType<LoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return loginUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUser>>
>;
export type LoginUserMutationBody = BodyType<LoginBody>;
export type LoginUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login
 */
export const useLoginUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  return useMutation(getLoginUserMutationOptions(options));
};

/**
 * @summary Logout
 */
export const getLogoutUserUrl = () => {
  return `/api/auth/logout`;
};

export const logoutUser = async (
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getLogoutUserUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logoutUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutUser>>,
    void
  > = () => {
    return logoutUser(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutUser>>
>;

export type LogoutUserMutationError = ErrorType<unknown>;

/**
 * @summary Logout
 */
export const useLogoutUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutUserMutationOptions(options));
};

/**
 * @summary Get current user
 */
export const getGetMeUrl = () => {
  return `/api/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<User> => {
  return customFetch<User>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user profile
 */
export const getGetUserUrl = (userId: number) => {
  return `/api/users/${userId}`;
};

export const getUser = async (
  userId: number,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getGetUserUrl(userId), {
    ...options,
    method: "GET",
  });
};

export const getGetUserQueryKey = (userId: number) => {
  return [`/api/users/${userId}`] as const;
};

export const getGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({
    signal,
  }) => getUser(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUser>>
>;
export type GetUserQueryError = ErrorType<unknown>;

/**
 * @summary Get user profile
 */

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<unknown>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserQueryOptions(userId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get children linked to a parent account
 */
export const getGetChildrenUrl = (userId: number) => {
  return `/api/users/${userId}/children`;
};

export const getChildren = async (
  userId: number,
  options?: RequestInit,
): Promise<Child[]> => {
  return customFetch<Child[]>(getGetChildrenUrl(userId), {
    ...options,
    method: "GET",
  });
};

export const getGetChildrenQueryKey = (userId: number) => {
  return [`/api/users/${userId}/children`] as const;
};

export const getGetChildrenQueryOptions = <
  TData = Awaited<ReturnType<typeof getChildren>>,
  TError = ErrorType<unknown>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getChildren>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChildrenQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChildren>>> = ({
    signal,
  }) => getChildren(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChildren>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetChildrenQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChildren>>
>;
export type GetChildrenQueryError = ErrorType<unknown>;

/**
 * @summary Get children linked to a parent account
 */

export function useGetChildren<
  TData = Awaited<ReturnType<typeof getChildren>>,
  TError = ErrorType<unknown>,
>(
  userId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getChildren>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetChildrenQueryOptions(userId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a child profile
 */
export const getAddChildUrl = (userId: number) => {
  return `/api/users/${userId}/children`;
};

export const addChild = async (
  userId: number,
  addChildBody: AddChildBody,
  options?: RequestInit,
): Promise<Child> => {
  return customFetch<Child>(getAddChildUrl(userId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addChildBody),
  });
};

export const getAddChildMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addChild>>,
    TError,
    { userId: number; data: BodyType<AddChildBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addChild>>,
  TError,
  { userId: number; data: BodyType<AddChildBody> },
  TContext
> => {
  const mutationKey = ["addChild"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addChild>>,
    { userId: number; data: BodyType<AddChildBody> }
  > = (props) => {
    const { userId, data } = props ?? {};

    return addChild(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddChildMutationResult = NonNullable<
  Awaited<ReturnType<typeof addChild>>
>;
export type AddChildMutationBody = BodyType<AddChildBody>;
export type AddChildMutationError = ErrorType<unknown>;

/**
 * @summary Add a child profile
 */
export const useAddChild = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addChild>>,
    TError,
    { userId: number; data: BodyType<AddChildBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addChild>>,
  TError,
  { userId: number; data: BodyType<AddChildBody> },
  TContext
> => {
  return useMutation(getAddChildMutationOptions(options));
};

/**
 * @summary Get available subscription plans
 */
export const getGetSubscriptionPlansUrl = () => {
  return `/api/subscriptions/plans`;
};

export const getSubscriptionPlans = async (
  options?: RequestInit,
): Promise<SubscriptionPlan[]> => {
  return customFetch<SubscriptionPlan[]>(getGetSubscriptionPlansUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSubscriptionPlansQueryKey = () => {
  return [`/api/subscriptions/plans`] as const;
};

export const getGetSubscriptionPlansQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscriptionPlans>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSubscriptionPlans>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubscriptionPlansQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSubscriptionPlans>>
  > = ({ signal }) => getSubscriptionPlans({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubscriptionPlans>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSubscriptionPlansQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscriptionPlans>>
>;
export type GetSubscriptionPlansQueryError = ErrorType<unknown>;

/**
 * @summary Get available subscription plans
 */

export function useGetSubscriptionPlans<
  TData = Awaited<ReturnType<typeof getSubscriptionPlans>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSubscriptionPlans>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSubscriptionPlansQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Subscribe to a plan
 */
export const getCreateSubscriptionUrl = () => {
  return `/api/subscriptions`;
};

export const createSubscription = async (
  createSubscriptionBody: CreateSubscriptionBody,
  options?: RequestInit,
): Promise<Subscription> => {
  return customFetch<Subscription>(getCreateSubscriptionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSubscriptionBody),
  });
};

export const getCreateSubscriptionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSubscription>>,
    TError,
    { data: BodyType<CreateSubscriptionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSubscription>>,
  TError,
  { data: BodyType<CreateSubscriptionBody> },
  TContext
> => {
  const mutationKey = ["createSubscription"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSubscription>>,
    { data: BodyType<CreateSubscriptionBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createSubscription(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSubscription>>
>;
export type CreateSubscriptionMutationBody = BodyType<CreateSubscriptionBody>;
export type CreateSubscriptionMutationError = ErrorType<unknown>;

/**
 * @summary Subscribe to a plan
 */
export const useCreateSubscription = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSubscription>>,
    TError,
    { data: BodyType<CreateSubscriptionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createSubscription>>,
  TError,
  { data: BodyType<CreateSubscriptionBody> },
  TContext
> => {
  return useMutation(getCreateSubscriptionMutationOptions(options));
};

/**
 * @summary Get current user's subscription
 */
export const getGetMySubscriptionUrl = () => {
  return `/api/subscriptions/me`;
};

export const getMySubscription = async (
  options?: RequestInit,
): Promise<Subscription> => {
  return customFetch<Subscription>(getGetMySubscriptionUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMySubscriptionQueryKey = () => {
  return [`/api/subscriptions/me`] as const;
};

export const getGetMySubscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMySubscription>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMySubscriptionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMySubscription>>
  > = ({ signal }) => getMySubscription({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMySubscription>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMySubscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMySubscription>>
>;
export type GetMySubscriptionQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user's subscription
 */

export function useGetMySubscription<
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMySubscription>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMySubscriptionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get today's MK Box content
 */
export const getGetTodayContentUrl = () => {
  return `/api/daily-content/today`;
};

export const getTodayContent = async (
  options?: RequestInit,
): Promise<DailyContent> => {
  return customFetch<DailyContent>(getGetTodayContentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetTodayContentQueryKey = () => {
  return [`/api/daily-content/today`] as const;
};

export const getGetTodayContentQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodayContent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTodayContent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodayContentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodayContent>>> = ({
    signal,
  }) => getTodayContent({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTodayContent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTodayContentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTodayContent>>
>;
export type GetTodayContentQueryError = ErrorType<unknown>;

/**
 * @summary Get today's MK Box content
 */

export function useGetTodayContent<
  TData = Awaited<ReturnType<typeof getTodayContent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getTodayContent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTodayContentQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all daily content (history)
 */
export const getListDailyContentUrl = () => {
  return `/api/daily-content`;
};

export const listDailyContent = async (
  options?: RequestInit,
): Promise<DailyContent[]> => {
  return customFetch<DailyContent[]>(getListDailyContentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListDailyContentQueryKey = () => {
  return [`/api/daily-content`] as const;
};

export const getListDailyContentQueryOptions = <
  TData = Awaited<ReturnType<typeof listDailyContent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listDailyContent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDailyContentQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listDailyContent>>
  > = ({ signal }) => listDailyContent({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDailyContent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListDailyContentQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDailyContent>>
>;
export type ListDailyContentQueryError = ErrorType<unknown>;

/**
 * @summary List all daily content (history)
 */

export function useListDailyContent<
  TData = Awaited<ReturnType<typeof listDailyContent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listDailyContent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDailyContentQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get specific daily content
 */
export const getGetDailyContentUrl = (contentId: number) => {
  return `/api/daily-content/${contentId}`;
};

export const getDailyContent = async (
  contentId: number,
  options?: RequestInit,
): Promise<DailyContent> => {
  return customFetch<DailyContent>(getGetDailyContentUrl(contentId), {
    ...options,
    method: "GET",
  });
};

export const getGetDailyContentQueryKey = (contentId: number) => {
  return [`/api/daily-content/${contentId}`] as const;
};

export const getGetDailyContentQueryOptions = <
  TData = Awaited<ReturnType<typeof getDailyContent>>,
  TError = ErrorType<unknown>,
>(
  contentId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDailyContent>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDailyContentQueryKey(contentId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyContent>>> = ({
    signal,
  }) => getDailyContent(contentId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!contentId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDailyContent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDailyContentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDailyContent>>
>;
export type GetDailyContentQueryError = ErrorType<unknown>;

/**
 * @summary Get specific daily content
 */

export function useGetDailyContent<
  TData = Awaited<ReturnType<typeof getDailyContent>>,
  TError = ErrorType<unknown>,
>(
  contentId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDailyContent>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDailyContentQueryOptions(contentId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Mark content as viewed (tracked for fast-forward detection)
 */
export const getMarkContentViewedUrl = (contentId: number) => {
  return `/api/daily-content/${contentId}/view`;
};

export const markContentViewed = async (
  contentId: number,
  markViewedBody: MarkViewedBody,
  options?: RequestInit,
): Promise<ContentView> => {
  return customFetch<ContentView>(getMarkContentViewedUrl(contentId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(markViewedBody),
  });
};

export const getMarkContentViewedMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markContentViewed>>,
    TError,
    { contentId: number; data: BodyType<MarkViewedBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markContentViewed>>,
  TError,
  { contentId: number; data: BodyType<MarkViewedBody> },
  TContext
> => {
  const mutationKey = ["markContentViewed"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markContentViewed>>,
    { contentId: number; data: BodyType<MarkViewedBody> }
  > = (props) => {
    const { contentId, data } = props ?? {};

    return markContentViewed(contentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MarkContentViewedMutationResult = NonNullable<
  Awaited<ReturnType<typeof markContentViewed>>
>;
export type MarkContentViewedMutationBody = BodyType<MarkViewedBody>;
export type MarkContentViewedMutationError = ErrorType<unknown>;

/**
 * @summary Mark content as viewed (tracked for fast-forward detection)
 */
export const useMarkContentViewed = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markContentViewed>>,
    TError,
    { contentId: number; data: BodyType<MarkViewedBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof markContentViewed>>,
  TError,
  { contentId: number; data: BodyType<MarkViewedBody> },
  TContext
> => {
  return useMutation(getMarkContentViewedMutationOptions(options));
};

/**
 * @summary Submit a voice recording
 */
export const getSubmitRecordingUrl = () => {
  return `/api/recordings`;
};

export const submitRecording = async (
  submitRecordingBody: SubmitRecordingBody,
  options?: RequestInit,
): Promise<Recording> => {
  return customFetch<Recording>(getSubmitRecordingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(submitRecordingBody),
  });
};

export const getSubmitRecordingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitRecording>>,
    TError,
    { data: BodyType<SubmitRecordingBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitRecording>>,
  TError,
  { data: BodyType<SubmitRecordingBody> },
  TContext
> => {
  const mutationKey = ["submitRecording"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitRecording>>,
    { data: BodyType<SubmitRecordingBody> }
  > = (props) => {
    const { data } = props ?? {};

    return submitRecording(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitRecordingMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitRecording>>
>;
export type SubmitRecordingMutationBody = BodyType<SubmitRecordingBody>;
export type SubmitRecordingMutationError = ErrorType<unknown>;

/**
 * @summary Submit a voice recording
 */
export const useSubmitRecording = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitRecording>>,
    TError,
    { data: BodyType<SubmitRecordingBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof submitRecording>>,
  TError,
  { data: BodyType<SubmitRecordingBody> },
  TContext
> => {
  return useMutation(getSubmitRecordingMutationOptions(options));
};

/**
 * @summary List recordings for current user's child
 */
export const getListRecordingsUrl = () => {
  return `/api/recordings`;
};

export const listRecordings = async (
  options?: RequestInit,
): Promise<Recording[]> => {
  return customFetch<Recording[]>(getListRecordingsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListRecordingsQueryKey = () => {
  return [`/api/recordings`] as const;
};

export const getListRecordingsQueryOptions = <
  TData = Awaited<ReturnType<typeof listRecordings>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listRecordings>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListRecordingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecordings>>> = ({
    signal,
  }) => listRecordings({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listRecordings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListRecordingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRecordings>>
>;
export type ListRecordingsQueryError = ErrorType<unknown>;

/**
 * @summary List recordings for current user's child
 */

export function useListRecordings<
  TData = Awaited<ReturnType<typeof listRecordings>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listRecordings>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListRecordingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current user's child progress and points
 */
export const getGetMyProgressUrl = () => {
  return `/api/progress/me`;
};

export const getMyProgress = async (
  options?: RequestInit,
): Promise<Progress> => {
  return customFetch<Progress>(getGetMyProgressUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyProgressQueryKey = () => {
  return [`/api/progress/me`] as const;
};

export const getGetMyProgressQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyProgress>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyProgress>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyProgressQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyProgress>>> = ({
    signal,
  }) => getMyProgress({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyProgress>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyProgressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyProgress>>
>;
export type GetMyProgressQueryError = ErrorType<unknown>;

/**
 * @summary Get current user's child progress and points
 */

export function useGetMyProgress<
  TData = Awaited<ReturnType<typeof getMyProgress>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyProgress>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyProgressQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current streak and completion history
 */
export const getGetStreakUrl = () => {
  return `/api/progress/streak`;
};

export const getStreak = async (options?: RequestInit): Promise<Streak> => {
  return customFetch<Streak>(getGetStreakUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetStreakQueryKey = () => {
  return [`/api/progress/streak`] as const;
};

export const getGetStreakQueryOptions = <
  TData = Awaited<ReturnType<typeof getStreak>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStreak>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStreakQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStreak>>> = ({
    signal,
  }) => getStreak({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStreak>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStreakQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStreak>>
>;
export type GetStreakQueryError = ErrorType<unknown>;

/**
 * @summary Get current streak and completion history
 */

export function useGetStreak<
  TData = Awaited<ReturnType<typeof getStreak>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStreak>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStreakQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get quarterly progress summary
 */
export const getGetProgressSummaryUrl = () => {
  return `/api/progress/summary`;
};

export const getProgressSummary = async (
  options?: RequestInit,
): Promise<ProgressSummary> => {
  return customFetch<ProgressSummary>(getGetProgressSummaryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetProgressSummaryQueryKey = () => {
  return [`/api/progress/summary`] as const;
};

export const getGetProgressSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getProgressSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getProgressSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProgressSummaryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProgressSummary>>
  > = ({ signal }) => getProgressSummary({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProgressSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProgressSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProgressSummary>>
>;
export type GetProgressSummaryQueryError = ErrorType<unknown>;

/**
 * @summary Get quarterly progress summary
 */

export function useGetProgressSummary<
  TData = Awaited<ReturnType<typeof getProgressSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getProgressSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetProgressSummaryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get quarterly leaderboard (top improved kids)
 */
export const getGetLeaderboardUrl = () => {
  return `/api/rewards/leaderboard`;
};

export const getLeaderboard = async (
  options?: RequestInit,
): Promise<LeaderboardEntry[]> => {
  return customFetch<LeaderboardEntry[]>(getGetLeaderboardUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetLeaderboardQueryKey = () => {
  return [`/api/rewards/leaderboard`] as const;
};

export const getGetLeaderboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaderboard>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLeaderboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLeaderboardQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeaderboard>>> = ({
    signal,
  }) => getLeaderboard({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaderboard>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLeaderboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaderboard>>
>;
export type GetLeaderboardQueryError = ErrorType<unknown>;

/**
 * @summary Get quarterly leaderboard (top improved kids)
 */

export function useGetLeaderboard<
  TData = Awaited<ReturnType<typeof getLeaderboard>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLeaderboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLeaderboardQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List available quarterly rewards/trips
 */
export const getListRewardsUrl = () => {
  return `/api/rewards`;
};

export const listRewards = async (options?: RequestInit): Promise<Reward[]> => {
  return customFetch<Reward[]>(getListRewardsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListRewardsQueryKey = () => {
  return [`/api/rewards`] as const;
};

export const getListRewardsQueryOptions = <
  TData = Awaited<ReturnType<typeof listRewards>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listRewards>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListRewardsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRewards>>> = ({
    signal,
  }) => listRewards({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listRewards>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListRewardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRewards>>
>;
export type ListRewardsQueryError = ErrorType<unknown>;

/**
 * @summary List available quarterly rewards/trips
 */

export function useListRewards<
  TData = Awaited<ReturnType<typeof listRewards>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listRewards>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListRewardsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
